### ISSUE TITLE
Broken links with Missing Files in 2019-07 - azure-pipelines-for-k8s

### ISSUE THREAD

**Issue by micgruber** [mathieu-benoit/mathieu-benoit.github.io#28]
Hi,

I would be very thankful if you can provide the missing files from your article:

- azure-pipelines.yml
- build-steps-template.yml
- stage-steps-template.yml

https://github.com/Azure/phippyandfriends/blob/mathieu-benoit/azure-pipelines/common/build-steps-template.yml

Best regards

**Comment by mathieu-benoit** [comment]
Thanks for reaching out @micgruber, let me see what I could find for you. Just curious, where did you see those files referenced? If on my blog, could you please provide the URL, I will fix the broken links in the meantime. Thanks.

**Comment by micgruber** [comment]
Hi @mathieu-benoit,

sorry, I provided the wrong link: https://alwaysupalwayson.com/posts/2019/07/azure-pipelines-for-k8s/

Best regards

**Comment by mathieu-benoit** [comment]
Got it, thanks again for reporting the broken links, much appreciated!

Actually all those files are directly in `master` branch there: https://github.com/Azure/phippyandfriends/. Please keep in mind that since I wrote that article you are referencing you may notice few differences with the current pipelines definitions but the ideas are here and you could get inspiration of them. Hope that helps!
- https://github.com/Azure/phippyandfriends/tree/master/common
- `ci-pipeline.yml` and `cd-pipeline.yml` for each app, for example in there: https://github.com/Azure/phippyandfriends/tree/master/captainkube

I will soon fix the broken links, keeping that issue open for now, and I will close it accordingly.

**Comment by micgruber** [comment]
Hi @mathieu-benoit,

thank you very much for the quick reply. Maybe I can ask you one more question regarding you article:

In section "4. Azure Key Vault to store and retrieve the secrets" you mentioned that you store your secrects in an key vault. Do you also store there application settings like a db connection or how do you manage application settings through your pipeline?

Best regards

**Comment by mathieu-benoit** [comment]
Sure, as far as I recall when I did it (disclaimer, I don't have anymore access to an Azure environment, I recently switch to Google Cloud), once you add the Variable Group grabbing the Key Vault secrets like illustrated [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#link-secrets-from-an-azure-key-vault), you could then use them as usual variables in your pipelines then, like described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#use-a-variable-group). Hope that helps!

**Comment by micgruber** [comment]
Hi @mathieu-benoit,

thanks for your help.

Best regards

**Comment by micgruber** [comment]
Hi @mathieu-benoit,

just one more question :) Have you also tried kubernetes secrets instead of the key vault?

Best regards

**Comment by mathieu-benoit** [comment]
Taken into account by this commit: https://github.com/mathieu-benoit/myblog/commit/224ccfd5702e7113b66ac59d29ed654ae0905dc6. Thanks again for raising the issue!

**Comment by mathieu-benoit** [comment]
@micgruber, regarding your last question about k8s secrets, I haven't because in this specific scope what I would like to do is protect the variables stored and needed in Azure DevOps, so no relationship with Kubernetes for those variables/values stored in Azure KeyVault.

**Comment by micgruber** [comment]
Hi @mathieu-benoit,

thank you very much for your help.

Best regards
